name: intheloopapp
version: 1.2.107+120
publish_to: none
description: mobile app for tapped.
environment: 
  sdk: '>=3.0.0 <4.0.0'

dependencies: 
  algolia: 1.1.2
  animations: 2.0.11
  app_settings: 5.1.1
#  audio_service: 0.18.13
  avatar_stack: 1.2.0
  badges: 3.1.2
  bloc: 8.1.4
  bloc_test: 9.1.7
  cached: 1.6.1
  cached_annotation: 1.7.0
  cached_network_image: 3.3.1
  cancelable_retry: 0.1.0+1
  card_banner: 0.0.1+2
  cloud_firestore: 5.0.0
  cloud_functions: 5.0.0
  confetti: 0.7.0
  crypto: 3.0.3
  cupertino_icons: 1.0.8
  currency_text_input_formatter: 2.2.3
  email_validator: 2.1.17
  enum_to_string: 2.0.1
  equatable: 2.0.5
  feedback: 3.1.0
  file_picker: 6.2.1
  firebase_analytics: 11.0.0
  firebase_auth: 5.0.0
  firebase_core: 3.0.0
  firebase_core_platform_interface: 5.0.0
  firebase_crashlytics: 4.0.0
  firebase_in_app_messaging: 0.8.0
  firebase_messaging: 15.0.0
  firebase_performance: 0.10.0
  firebase_remote_config: 5.0.0
  firebase_storage: 12.0.0
  fl_chart: ^0.68.0
  flutter: 
    sdk: flutter
  flutter_app_badger: 1.5.0
  flutter_bloc: 8.1.5
  flutter_cache_manager: 3.3.1
  flutter_easyloading: 3.0.5
  flutter_google_places_sdk: 0.3.9
  flutter_image_compress: 2.3.0
  flutter_map: 6.2.1
  flutter_map_heatmap: 0.0.7
  flutter_map_marker_cluster: ^1.3.6
  flutter_map_tile_caching: 9.0.1
  flutter_native_splash: 2.4.0
  flutter_rating_bar: 4.0.1
  flutter_slidable: 3.1.0
  flutter_spinkit: 5.2.1
  flutter_stripe: 10.1.1
  flutter_svg: 2.0.10+1
  font_awesome_flutter: 10.7.0
  formz: 0.7.0
  fpdart: 1.1.0
  freezed_annotation: 2.4.1
  gallery_saver: 2.3.2
  gauge_indicator: 0.4.3
  geolocator: 12.0.0
  georange: 1.0.0
  google_fonts: 6.2.1
  google_sign_in: 6.2.1
  group_radio_button: 1.3.0
  hydrated_bloc: 9.1.5
  image_downloader:  # 0.31.0
    git:
      url: https://github.com/ko2ic/image_downloader.git
  image_gallery_saver: 2.0.3
  image_picker: 1.1.2
  intl: 0.19.0
  isar_flutter_libs: 3.1.0+1
  json_annotation: 4.9.0
#  just_audio: 0.9.38
  linkify: 5.0.0
  logging: 1.2.0
  maps_launcher: 2.2.1
  mime: 1.0.5
#  modal_bottom_sheet:
#    git:
#      url: https://github.com/jamesblasco/modal_bottom_sheet
#      path: modal_bottom_sheet
  multi_select_flutter: 4.1.3
  package_info_plus: 8.0.0
  path: 1.9.0
  path_provider: 2.1.3
  permission_handler: 11.3.1
  photo_view: 0.14.0
  pull_down_button: 0.9.4
  purchases_flutter: 6.29.3
  quiver: 3.2.1
  readmore: 3.0.0
  rive: 0.13.7
  rxdart: 0.27.7
  scroll_snap_list: 0.9.1
  share_plus: 8.0.3
  sign_in_with_apple: 6.1.0
  skeleton_animation: 0.1.4
  skeleton_text: 3.0.1
#  skeletons: 0.0.3
  skeletons:
    git:
      url: https://github.com/makslara/skeletons
      ref: fix-path-apptheme
  stack_trace: 1.11.1
#  stream_chat_flutter:
#    git:
#      url: https://github.com/easyhour/stream-chat-flutter
#      path: packages/stream_chat_flutter
#      ref: beta
  stream_chat_flutter: 7.2.1
#  stream_chat_flutter: 8.0.0-beta.3
#  stream_video_flutter: 0.3.1
  timeago: 3.6.1
  timelines: 0.1.0
  transparent_pointer: 1.0.1
  app_links: 6.1.1
  upgrader: 10.3.0
  url_launcher: 6.3.0
  uuid: 4.2.1
  visibility_detector: 0.4.0+2
  modal_bottom_sheet: 3.0.0
  screenshot: 3.0.0
  qr_flutter: 4.1.0
  dio: 5.4.3+1
  lucide_icons: ^0.257.0

dev_dependencies: 
  build_runner: ^2.4.8
  dart_code_metrics: ^5.7.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  json_serializable: ^6.3.1
  mockito: ^5.0.16
  pubspec_dependency_sorter: ^1.0.3
  very_good_analysis: ^5.0.0+1

dependency_overrides:
  audio_video_progress_bar: 2.0.3
  connectivity_plus: 5.0.2
  http: 0.13.3
  uuid: 4.2.1
  photo_manager: 3.0.0

flutter_icons: 
  image_path_ios: assets/app_icon_ios.png
#  image_path_android: assets/app_icon_ios.png
#  android: true
  ios: true
  remove_alpha_ios: true

flutter: 
  assets: 
    - assets/
    - assets/cities/
    - assets/layers/
    - assets/default_images/
  uses-material-design: true
