name: intheloopapp
version: 1.2.76+89
publish_to: none
description: Mobile app for Tapped.
environment: 
  sdk: '>=3.0.0 <4.0.0'

dependencies: 
  algolia: 1.1.2
  animations: 2.0.11
  audio_service: 0.18.12
  avatar_stack: ^1.2.0
  badges: 3.1.2
  bloc: 8.1.2
  bloc_test: 9.1.5
  cached: 1.6.1
  cached_annotation: 1.6.0
  cached_network_image: 3.3.1
  cancelable_retry: 0.1.0+1
  card_banner: 0.0.1+2
  cloud_firestore: 4.14.0
  cloud_functions: 4.6.0
  confetti: 0.7.0
  crypto: 3.0.3
  cupertino_icons: 1.0.6
  currency_text_input_formatter: 2.1.11
  email_validator: 2.1.17
  enum_to_string: 2.0.1
  equatable: 2.0.5
  feedback: 3.0.0
  file_picker: ^6.1.1
  firebase_analytics: 10.8.0
  firebase_auth: 4.16.0
  firebase_core: 2.24.2
  firebase_core_platform_interface: 5.0.0
  firebase_crashlytics: 3.4.9
  firebase_in_app_messaging: 0.7.4+8
  firebase_messaging: 14.7.10
  firebase_performance: 0.9.3+8
  firebase_remote_config: 4.3.8
  firebase_storage: 11.6.0
  fl_chart: ^0.66.2
  flutter: 
    sdk: flutter
  flutter_app_badger: 1.5.0
  flutter_bloc: 8.1.3
  flutter_cache_manager: 3.3.1
  flutter_easyloading: ^3.0.5
  flutter_google_places_sdk: 0.3.7
  flutter_image_compress: 2.1.0
  flutter_map: ^6.1.0
  flutter_map_heatmap: ^0.0.7
  flutter_map_marker_cluster: ^1.3.4
  flutter_map_tile_caching: ^9.0.0-dev.5
  flutter_native_splash: ^2.3.9
  flutter_slidable: 3.0.1
  flutter_spinkit: 5.2.0
  flutter_stripe: 10.0.0
  flutter_svg: 2.0.9
  font_awesome_flutter: 10.6.0
  formz: 0.6.1
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.1
  gallery_saver: ^2.3.2
  geolocator: ^10.1.0
  georange: 1.0.0
  google_fonts: 6.1.0
  google_sign_in: ^6.2.1
  group_radio_button: 1.3.0
  hydrated_bloc: 9.1.3
  image_downloader:  # 0.31.0
    git:
      url: https://github.com/ko2ic/image_downloader.git
  image_gallery_saver: ^2.0.3
  image_picker: ^1.0.7
  intl: 0.18.1
  isar_flutter_libs: ^3.1.0+1
  json_annotation: 4.8.1
  just_audio: 0.9.36
  like_button: 2.0.5
  linkify: 5.0.0
  logging: 1.2.0
  maps_launcher: 2.2.0
  mime: ^1.0.5
  modal_bottom_sheet:
    git:
      url: https://github.com/jamesblasco/modal_bottom_sheet
      path: modal_bottom_sheet
  multi_select_flutter: 4.1.3
  package_info_plus: 5.0.1
  path: 1.8.3
  path_provider: ^2.1.2
  photo_view: ^0.14.0
  pull_down_button: 0.9.3
  purchases_flutter: ^6.5.1
  quiver: 3.2.1
  readmore: ^2.2.0
  rive: ^0.12.4
  rxdart: 0.27.7
  scroll_snap_list: 0.9.1
  share_plus: 7.2.1
  sign_in_with_apple: 5.0.0
  skeleton_animation: 0.1.4
  skeleton_text: 3.0.1
  skeletons: 0.0.3
  stack_trace: ^1.11.1
  stream_chat_flutter: 8.0.0-beta.1
#  stream_video_flutter: 0.3.1
  timeago: 3.6.0
  transparent_pointer: 1.0.0
  uni_links: 0.5.1
  url_launcher: ^6.2.4
  uuid: 3.0.7
  visibility_detector: 0.4.0+2

dev_dependencies: 
  build_runner: ^2.4.8
  dart_code_metrics: ^5.7.0
  flutter_launcher_icons: ^0.13.0
  flutter_lints: ^3.0.1
  flutter_test: 
    sdk: flutter
  freezed: ^2.4.6
  json_serializable: ^6.3.1
  mockito: ^5.0.16
  pubspec_dependency_sorter: ^1.0.3
  very_good_analysis: ^5.0.0+1

dependency_overrides: 
  connectivity_plus: 5.0.1
  http: 0.13.3 

flutter_icons: 
  image_path_ios: assets/app_icon_ios.png
  image_path_android: assets/app_icon_ios.png
  android: true
  ios: true
  remove_alpha_ios: true

flutter: 
  assets: 
    - assets/
    - assets/cities/
    - assets/aesthetics/
    - assets/layers/
    - assets/default_images/
  uses-material-design: true
