name: intheloopapp
version: 1.1.48+59
publish_to: none
description: Mobile app for Tapped.
environment: 
  sdk: '>=3.0.0 <4.0.0'

dependencies: 
  algolia: 1.1.2
  animations: 2.0.7
  audio_service: 0.18.10
  badges: 3.1.1
  bloc: 8.1.2
  bloc_test: 9.1.3
  cached_network_image: 3.2.3
  cancelable_retry: 0.1.0+1
  card_banner: 0.0.1+2
  cloud_firestore: 4.8.1
  cloud_functions: 4.3.3
  connectivity_plus: 4.0.1
  crypto: 3.0.3
  cupertino_icons: 1.0.5
  currency_text_input_formatter: 2.1.10
  email_validator: 2.1.17
  enum_to_string: 2.0.1
  equatable: 2.0.5
  file_picker: 5.3.2
  firebase_analytics: 10.4.3
  firebase_auth: 4.6.3
  firebase_core: 2.14.0
  firebase_core_platform_interface: 4.8.0
  firebase_crashlytics: 3.3.3
  firebase_dynamic_links: 5.3.3
  firebase_in_app_messaging: 0.7.3+3
  firebase_messaging: 14.6.3
  firebase_performance: 0.9.2+3
  firebase_remote_config: 4.2.3
  firebase_storage: 11.2.3
  flutter: 
    sdk: flutter
  flutter_app_badger: 1.5.0
  flutter_bloc: 8.1.3
  flutter_cache_manager: 3.3.1
  flutter_google_places_sdk: 0.3.2+9
  flutter_image_compress: 2.0.3
  flutter_native_splash: 2.3.1
  flutter_slidable: 3.0.0
  flutter_spinkit: 5.2.0
  flutter_stripe: 9.3.0
  flutter_svg: 2.0.7
  font_awesome_flutter: 10.5.0
  formz: 0.6.0
  georange: 1.0.0
  google_fonts: 4.0.4
  google_sign_in: 6.1.4
  group_radio_button: 1.3.0
  hydrated_bloc: 9.1.2
  image_picker: 1.0.1
  intl: 0.18.1
  json_annotation: 4.8.1
  just_audio: 0.9.34
  like_button: 2.0.5
  linkify: 5.0.0
  logging: 1.2.0
  modal_bottom_sheet:
    git:
      url: https://github.com/jamesblasco/modal_bottom_sheet
      path: modal_bottom_sheet
  multi_select_flutter: 4.1.3
  package_info_plus: 4.0.2
  path: 1.8.3
  path_provider: 2.0.15
  pull_down_button: 0.9.1
  quiver: 3.2.1
  rive: 0.11.4
  rxdart: 0.27.7
  share_plus: 7.0.2
  sign_in_with_apple: 5.0.0
  skeleton_animation: 0.1.4
  skeleton_text: 3.0.0
  skeletons: 0.0.3
  stream_chat_flutter: 6.7.0
  stream_video_flutter: ^0.0.2
  timeago: 3.5.0
  transparent_pointer: 1.0.0
  url_launcher: 6.1.12
  uuid: 3.0.7
  visibility_detector: 0.4.0+2

dev_dependencies: 
  build_runner: ^2.0.6
  dart_code_metrics: ^5.7.0
  flutter_launcher_icons: ^0.13.0
  flutter_lints: ^2.0.1
  flutter_test: 
    sdk: flutter
  json_serializable: ^6.3.1
  mockito: ^5.0.16
  pubspec_dependency_sorter: ^1.0.3
  very_good_analysis: ^5.0.0+1

flutter_icons: 
  image_path_ios: assets/app_icon_ios.png
  image_path_android: assets/app_icon_ios.png
  android: true
  ios: true
  remove_alpha_ios: true

flutter: 
  assets: 
    - assets/
    - assets/cities/
    - assets/aesthetics/
  uses-material-design: true
